### ISSUE TITLE
Tooltip overflow in sidebar 'modal'

### ISSUE THREAD

**Issue by Link2Twenty** [adaptlearning/adapt_authoring#2414]
Currently, the tooltip can overflow the screen. I see in the past some code has been made to make these tooltips smaller.

![image](https://user-images.githubusercontent.com/3534427/63251033-d0604900-c264-11e9-922e-bcde275f389b.png)

https://github.com/adaptlearning/adapt_authoring/blob/af8e8d57d0922c74dc374f34b54a5d77fe169c9c/frontend/src/modules/scaffold/less/forms.less#L86-L119

If we added some code at line 103 we could move the tooltips to below the info circle. This wouldn't solve the problem for everyone but buys us around another 100px.

```css
.scaffold-items-modal & {
  left: 50%;
  transform: translateX(-50%);
  top: 105%;
}
```

![image](https://user-images.githubusercontent.com/3534427/63251397-8d52a580-c265-11e9-83a4-f1e7ef839e36.png)
